SELECT * FROM DWT_BRANCH_1.CUSTOMER;

SELECT * FROM DWT_BRANCH_2.CUSTOMER;

SELECT * FROM DWT_BRANCH_2.PLACE;

SELECT * FROM DWT_BRANCH_3.CUSTOMER;

SELECT * FROM CUSTOMER;

ALTER TABLE CUSTOMER
ADD COLUMN STREET VARCHAR(200);

ALTER TABLE CUSTOMER
ADD STREET VARCHAR(200); 

ALTER TABLE CUSTOMER
ADD STREET_NUMBER INT;

ALTER TABLE CUSTOMER
ADD ZIP_CODE INT;

ALTER TABLE CUSTOMER
ADD CITY VARCHAR(200);

SELECT ID, NAME, SURNAME, STR, NO, ZIP, PLACE, GEND, BDAY, COUNT(*) as duplicate_count 
FROM DWT_BRANCH_1.CUSTOMER
GROUP BY  ID, NAME, SURNAME, STR, NO, ZIP, PLACE, GEND, BDAY 
HAVING COUNT(*) > 1;

SELECT ID, NAME, SURNAME, STR, NO, ZIP, PLACE, GEND, BDAY, COUNT(*) as duplicate_count 
FROM DWT_BRANCH_3.CUSTOMER
GROUP BY  ID, NAME, SURNAME, STR, NO, ZIP, PLACE, GEND, BDAY 
HAVING COUNT(*) > 1;

SELECT SUBSTR(ZIP_PLACE, 1, INSTR(ZIP_PLACE, ' ') - 1) AS ZIP, SUBSTR(ZIP_PLACE, INSTR(ZIP_PLACE, ' ') + 1) AS CITY
FROM DWT_BRANCH_2.PLACE;

SELECT
    REGEXP_SUBSTR(STR_NO, '^(.*?)(\s+\d+[a-zA-Z]?)', 1, 1, NULL, 1) AS street,
    REGEXP_SUBSTR(STR_NO, '^(.*?)(\s+\d+[a-zA-Z]?)', 1, 1, NULL, 2) AS house_number
FROM
    DWT_BRANCH_2.PLACE;
    
/* 
POPULATION OF THE CUSTOMERS TABLE
*/
INSERT INTO CUSTOMER(FIRST_NAME, FAMILY_NAME, GENDER, DATE_OF_BIRTH, STREET, STREET_NUMBER, ZIP_CODE, CITY)
SELECT SURNAME, NAME, GEND, BDAY, STR, NO, ZIP, PLACE
FROM DWT_BRANCH_1.CUSTOMER;

INSERT INTO CUSTOMER(FIRST_NAME, FAMILY_NAME, GENDER, DATE_OF_BIRTH, STREET, STREET_NUMBER, ZIP_CODE, CITY)
SELECT SURNAME, NAME, GEND, BDAY, STR, NO, ZIP, PLACE
FROM DWT_BRANCH_3.CUSTOMER;

INSERT INTO CUSTOMER(FIRST_NAME, FAMILY_NAME, DATE_OF_BIRTH, STREET, STREET_NUMBER, ZIP_CODE, CITY)
SELECT 
    C.FIRSTNAME, 
    C.LASTNAME, 
    C.BDAY, 
    REGEXP_SUBSTR(P.STR_NO, '^(.*?)(\s+\d+[a-zA-Z]?)', 1, 1, NULL, 1) AS STREET,
    REGEXP_SUBSTR(P.STR_NO, '^(.*?)(\s+\d+[a-zA-Z]?)', 1, 1, NULL, 2) AS HOUSE_NUMBER,
    SUBSTR(P.ZIP_PLACE, 1, INSTR(P.ZIP_PLACE, ' ') - 1) AS ZIP, 
    SUBSTR(P.ZIP_PLACE, INSTR(P.ZIP_PLACE, ' ') + 1) AS CITY
FROM 
    DWT_BRANCH_2.CUSTOMER C
JOIN 
    DWT_BRANCH_2.PLACE P ON C.PLACEID = P.PLID;
    
UPDATE CUSTOMER
SET AGE_GROUP = 
    CASE
        WHEN TRUNC(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH) / 12) <= 15 THEN 'CHILD (0-15)'
        WHEN TRUNC(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH) / 12) BETWEEN 16 AND 19 THEN 'YOUNGSTER (16-19)'
        WHEN TRUNC(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH) / 12) BETWEEN 20 AND 29 THEN 'YOUNG ADULT (20-29)'
        WHEN TRUNC(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH) / 12) BETWEEN 30 AND 49 THEN 'ADULT (30-49)'
        ELSE 'OLD ADULT (>50)'
    END;
    
/* 
FINDING DUPLICATES 
IN THE COSTUMERS TABLE
*/
SELECT FIRST_NAME, FAMILY_NAME, DATE_OF_BIRTH, STREET, STREET_NUMBER, ZIP_CODE, CITY, COUNT(*) AS duplicate_count
FROM CUSTOMER
GROUP BY FIRST_NAME, FAMILY_NAME, DATE_OF_BIRTH, STREET, STREET_NUMBER, ZIP_CODE, CITY
HAVING COUNT(*) > 1;

/* 
DELETING DUPLICATES IN THE CUSTUMER TABLE
*/
DELETE FROM CUSTOMER
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM CUSTOMER
    GROUP BY FIRST_NAME, FAMILY_NAME, DATE_OF_BIRTH, STREET, STREET_NUMBER, ZIP_CODE, CITY
);

SELECT * FROM DWT_BRANCH_1.PRODUCTS;

SELECT * FROM DWT_BRANCH_2.PRODUCT;

SELECT * FROM DWT_BRANCH_3.PRODUCT;

SELECT * FROM DWT_BRANCH_3."ORDER";
SELECT * FROM DWT_BRANCH_3.BOTTLE;

SELECT * FROM BRANCH3_SORT;

SELECT * FROM PRODUCT;

SELECT * FROM BRANCH;

ALTER TABLE PRODUCT
ADD SID INT;

ALTER TABLE PRODUCT
ADD CONSTRAINT fk_SORT_CATEGORY
FOREIGN KEY (SID)
REFERENCES BRANCH3_SORT (SID);

ALTER TABLE PRODUCT
ADD PRODUCT_NAME VARCHAR(200);

ALTER TABLE PRODUCT
ADD VOLUME DECIMAL(10,3);

ALTER TABLE PRODUCT
ADD PRICE DECIMAL(10,4);

/* 
POPULATION OF THE PRODUCT TABLE
*/
INSERT INTO PRODUCT (SID, PRODUCT_NAME, VOLUME, PRICE)
SELECT
    CASE
        WHEN SORT = 'Alkoholfrei' THEN 1
        WHEN SORT = 'Alkoholisch' THEN 2
    END AS SID,
    NAME,
    SZ,
    PRICE
FROM
    DWT_BRANCH_1.PRODUCTS;
    
INSERT INTO PRODUCT (SID, PRODUCT_NAME, VOLUME, PRICE)
SELECT
    CASE
        WHEN TYPE = 'Alkoholfrei' THEN 1
        WHEN TYPE = 'Alkoholisch' THEN 2
    END AS SID,
    LABEL,
    LITER,
    PRICE
FROM
    DWT_BRANCH_2.PRODUCT;


INSERT INTO PRODUCT(SID, PRODUCT_NAME, PRICE)
SELECT SID, NAME, PRICE
FROM DWT_BRANCH_3.PRODUCT;

/* 
POPULATION OF THE BRANCH3_SORT TABLE
*/
INSERT INTO branch3_sort(SID, NAME)
SELECT SID, NAME
FROM DWT_BRANCH_3.SORT;

/* 
POPULATION OF THE BRANCH TABLE
*/
INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, REGION)
VALUES (1, 'BRANCH 1', 'EAST');

INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, REGION)
VALUES (2, 'BRANCH 2', 'WEST');

INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, REGION)
VALUES (3, 'BRANCH 3', 'NORD');

INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, REGION)
VALUES (4, 'BRANCH 4', 'NORD');

INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, REGION)
VALUES (5, 'BRANCH 5', 'EAST');

INSERT INTO BRANCH (BRANCH_ID, BRANCH_NAME, REGION)
VALUES (6, 'BRANCH 6', 'WEST');

SELECT * FROM PERIODS;

ALTER TABLE PERIODS
MODIFY DAY DATE;

ALTER TABLE PERIODS
MODIFY WEEK NUMBER;

ALTER TABLE PERIODS
MODIFY MONTH NUMBER;

ALTER TABLE PERIODS
MODIFY QUARTER NUMBER;

ALTER TABLE PERIODS
MODIFY YEAR NUMBER;

/* 
POPULATION OF THE PERIODS TABLE
*/
INSERT INTO PERIODS (DAY, WEEK, MONTH, QUARTER, YEAR)
SELECT
    EXTRACT(DAY FROM TO_DATE(o."DATE", 'DD-MON-RR')) AS DAY,
    TO_NUMBER(TO_CHAR(TO_DATE(o."DATE", 'DD-MON-RR'), 'WW')) AS WEEK,
    TO_NUMBER(TO_CHAR(TO_DATE(o."DATE", 'DD-MON-RR'), 'MM')) AS MONTH,
    TO_NUMBER(TO_CHAR(TO_DATE(o."DATE", 'DD-MON-RR'), 'Q')) AS QUARTER,
    TO_NUMBER(TO_CHAR(TO_DATE(o."DATE", 'DD-MON-RR'), 'YYYY')) AS YEAR
FROM
    DWT_BRANCH_1."ORDER" o;
    
INSERT INTO PERIODS (DAY, WEEK, MONTH, QUARTER, YEAR)
SELECT
    EXTRACT(DAY FROM TO_DATE(o."DATE", 'DD-MON-RR')) AS DAY,
    TO_NUMBER(TO_CHAR(TO_DATE(o."DATE", 'DD-MON-RR'), 'WW')) AS WEEK,
    TO_NUMBER(TO_CHAR(TO_DATE(o."DATE", 'DD-MON-RR'), 'MM')) AS MONTH,
    TO_NUMBER(TO_CHAR(TO_DATE(o."DATE", 'DD-MON-RR'), 'Q')) AS QUARTER,
    TO_NUMBER(TO_CHAR(TO_DATE(o."DATE", 'DD-MON-RR'), 'YYYY')) AS YEAR
FROM
    DWT_BRANCH_3."ORDER" o;
    
INSERT INTO PERIODS (DAY, WEEK, MONTH, QUARTER, YEAR)
SELECT
    EXTRACT(DAY FROM TO_DATE(B."DATE", 'DD-MON-RR')) AS DAY,
    TO_NUMBER(TO_CHAR(TO_DATE(B."DATE", 'DD-MON-RR'), 'WW')) AS WEEK,
    TO_NUMBER(TO_CHAR(TO_DATE(B."DATE", 'DD-MON-RR'), 'MM')) AS MONTH,
    TO_NUMBER(TO_CHAR(TO_DATE(B."DATE", 'DD-MON-RR'), 'Q')) AS QUARTER,
    TO_NUMBER(TO_CHAR(TO_DATE(B."DATE", 'DD-MON-RR'), 'YYYY')) AS YEAR
FROM
    DWT_BRANCH_2.BUYS B;

SELECT * FROM PERIODS;
    
SELECT * FROM SALES;

SELECT * FROM DWT_BRANCH_1."ORDER";

/* 
POPULATION OF THE SALES TABLE
*/
INSERT INTO SALES (PERIOD_ID, PRODUCT_ID, CUSTOMER_ID, QUANTITY)
SELECT
    P.PERIOD_ID,
    B.PNUMBER,
    B.CNUMBER,
    B.AMOUNT
FROM
    DWT_BRANCH_2.BUYS B
JOIN
    PERIODS P ON P.DAY = EXTRACT(DAY FROM O."DATE")
           AND P.WEEK = TO_NUMBER(TO_CHAR(O."DATE", 'WW'))
           AND P.MONTH = TO_NUMBER(TO_CHAR(O."DATE", 'MM'))
           AND P.QUARTER = TO_NUMBER(TO_CHAR(O."DATE", 'Q'))
           AND P.YEAR = TO_NUMBER(TO_CHAR(O."DATE", 'YYYY'));

INSERT INTO SALES (PERIOD_ID, PRODUCT_ID, CUSTOMER_ID, QUANTITY)
SELECT
    P.PERIOD_ID,
    O.PRO,
    O.CSTMR,
    O.AMOUNT
FROM
    DWT_BRANCH_3."ORDER" O
JOIN
    PERIODS P ON P.DAY = EXTRACT(DAY FROM O."DATE")
           AND P.WEEK = TO_NUMBER(TO_CHAR(O."DATE", 'WW'))
           AND P.MONTH = TO_NUMBER(TO_CHAR(O."DATE", 'MM'))
           AND P.QUARTER = TO_NUMBER(TO_CHAR(O."DATE", 'Q'))
           AND P.YEAR = TO_NUMBER(TO_CHAR(O."DATE", 'YYYY'));
           
SELECT * FROM SALES;

/* 
CALCULATING TURNOVER IN BRANCH1, BRANCH2 AND BRANCH3
*/
SELECT CSTMR, SUM(AMOUNT) as turnover
FROM DWT_BRANCH_1."ORDER"
GROUP BY CSTMR;

SELECT CSTMR, SUM(AMOUNT) as turnover
FROM DWT_BRANCH_3."ORDER"
GROUP BY CSTMR;

SELECT CNUMBER, SUM(AMOUNT) as turnover
FROM DWT_BRANCH_2.BUYS
GROUP BY CNUMBER;

/* 
CALCULATING THE AMOUNT OF SALES IN LITTERS BASED ON TURNOVER IN BRANCH1 AND BRANCH2 
BRANCH3 HAS NO LINK TO THE VOLUME ATTRIBUTE IN THE BOTTLE TABLE.
*/
SELECT
    O.AMOUNT * P.SZ AS SalesVolumeInLiters
FROM
    DWT_BRANCH_1."ORDER" O
JOIN
    DWT_BRANCH_1.PRODUCTS P ON O.PRO = P.ID;
    
SELECT
    B.AMOUNT * P.LITER AS SalesVolumeInLiters
FROM
    DWT_BRANCH_2.BUYS B
JOIN
    DWT_BRANCH_2.PRODUCT P ON B.PNUMBER = P.NUM;









